/**********************************/
/* Table Name: 후기 */
/**********************************/
CREATE TABLE REVIEW(
		REVIEWNO                      		VARCHAR2(255)		 NOT NULL		 PRIMARY KEY,
		CONTENTS                       		VARCHAR2(1000)		 NOT NULL,
		RATING                         		NUMBER		 NOT NULL,
		RDATE                          		DATE		 NOT NULL,
		SHOESNO                       		NUMBER(9)		 NOT NULL,
		MEMBERNO                      		NUMBER(9)		 NOT NULL,
  FOREIGN KEY (SHOESNO) REFERENCES SHOES (SHOESNO),
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
);

COMMENT ON TABLE REVIEW is '후기';
COMMENT ON COLUMN REVIEW.REVIEWNO is '후기 번호';
COMMENT ON COLUMN REVIEW.CONTENTS is '후기 내용';
COMMENT ON COLUMN REVIEW.RATING is '후기 점수';
COMMENT ON COLUMN REVIEW.RDATE is '후기 작성일';
COMMENT ON COLUMN REVIEW.SHOESNO is '신발 번호';
COMMENT ON COLUMN REVIEW.MEMBERNO is '멤버 번호';

SELECT shoesno from shoes;
--1 2 3 4 5 6 7 9 10 11 12 26 29 31 32 33 34 35 36 37 38 39 40
select memberno from member;
--1 5 7 8 9 10 11 12 16 17 18 19 20 21 22 23 27

-- 테스트용 데이터 삽입
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발이 정말 편해요! 강력 추천합니다.', 5, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 1, 1);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '디자인이 마음에 들어요. 잘 샀습니다.', 4, TO_DATE('2024-06-02', 'YYYY-MM-DD'), 2, 5);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '품질이 조금 아쉽네요. 그래도 나쁘지 않아요.', 3, TO_DATE('2024-06-03', 'YYYY-MM-DD'), 3, 7);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '사이즈가 너무 작아요. 교환할 예정입니다.', 2, TO_DATE('2024-06-04', 'YYYY-MM-DD'), 4, 8);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '배송이 빨라서 좋았어요.', 5, TO_DATE('2024-06-05', 'YYYY-MM-DD'), 5, 9);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '가격 대비 만족합니다.', 4, TO_DATE('2024-06-06', 'YYYY-MM-DD'), 6, 10);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발이 너무 무거워요. 발이 아픕니다.', 1, TO_DATE('2024-06-07', 'YYYY-MM-DD'), 7, 11);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '색상이 생각보다 밝아요. 그래도 예뻐요.', 4, TO_DATE('2024-06-08', 'YYYY-MM-DD'), 9, 12);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '매우 만족합니다. 다음에 또 구매할게요.', 5, TO_DATE('2024-06-09', 'YYYY-MM-DD'), 10, 16);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '생각보다 사이즈가 크네요. 조금 불편해요.', 3, TO_DATE('2024-06-10', 'YYYY-MM-DD'), 11, 17);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발 끈이 쉽게 풀려요. 불편합니다.', 2, TO_DATE('2024-06-11', 'YYYY-MM-DD'), 12, 18);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '가볍고 편해요. 디자인도 마음에 듭니다.', 5, TO_DATE('2024-06-12', 'YYYY-MM-DD'), 26, 19);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '실망입니다. 퀄리티가 낮아요.', 1, TO_DATE('2024-06-13', 'YYYY-MM-DD'), 29, 20);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '착화감이 좋아서 자주 신고 다닙니다.', 4, TO_DATE('2024-06-14', 'YYYY-MM-DD'), 31, 21);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '사진과 똑같아요. 만족합니다.', 5, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 32, 22);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '냄새가 심해요. 실망입니다.', 2, TO_DATE('2024-06-16', 'YYYY-MM-DD'), 33, 23);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '아주 좋아요! 다음에도 구매할게요.', 5, TO_DATE('2024-06-17', 'YYYY-MM-DD'), 34, 27);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '배송이 느렸어요. 그래도 제품은 괜찮아요.', 3, TO_DATE('2024-06-18', 'YYYY-MM-DD'), 35, 1);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발이 너무 단단해서 발이 아파요.', 2, TO_DATE('2024-06-19', 'YYYY-MM-DD'), 36, 5);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '디자인이 너무 예뻐요. 만족합니다.', 5, TO_DATE('2024-06-20', 'YYYY-MM-DD'), 37, 7);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '크기가 딱 맞아서 좋아요.', 4, TO_DATE('2024-06-21', 'YYYY-MM-DD'), 38, 8);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '무난해요. 큰 기대는 안했어요.', 3, TO_DATE('2024-06-22', 'YYYY-MM-DD'), 39, 9);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발 바닥이 미끄러워요. 위험합니다.', 1, TO_DATE('2024-06-23', 'YYYY-MM-DD'), 40, 10);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '아주 가볍고 좋습니다. 매일 신고 다녀요.', 5, TO_DATE('2024-06-24', 'YYYY-MM-DD'), 1, 11);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '색상이 마음에 들어요. 예뻐요.', 4, TO_DATE('2024-06-25', 'YYYY-MM-DD'), 2, 12);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '퀄리티가 좋아서 만족합니다.', 5, TO_DATE('2024-06-26', 'YYYY-MM-DD'), 3, 16);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '조금 무거워요. 그래도 나쁘지 않아요.', 3, TO_DATE('2024-06-27', 'YYYY-MM-DD'), 4, 17);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '사이즈가 안 맞아요. 다시 주문해야겠어요.', 2, TO_DATE('2024-06-28', 'YYYY-MM-DD'), 5, 18);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '디자인이 독특해서 좋아요.', 4, TO_DATE('2024-06-29', 'YYYY-MM-DD'), 6, 19);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '착용감이 아주 좋아요.', 5, TO_DATE('2024-06-30', 'YYYY-MM-DD'), 7, 20);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '퀄리티가 조금 아쉬워요.', 3, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 9, 21);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발 끈이 쉽게 풀려서 불편해요.', 2, TO_DATE('2024-07-02', 'YYYY-MM-DD'), 10, 22);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '아주 만족해요. 자주 이용할게요.', 5, TO_DATE('2024-07-03', 'YYYY-MM-DD'), 11, 23);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '배송이 느려서 아쉬웠어요.', 3, TO_DATE('2024-07-04', 'YYYY-MM-DD'), 12, 27);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발이 너무 무겁고 불편해요.', 1, TO_DATE('2024-07-05', 'YYYY-MM-DD'), 26, 1);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '가볍고 편해요. 만족합니다.', 5, TO_DATE('2024-07-06', 'YYYY-MM-DD'), 29, 5);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '생각보다 색상이 달라요.', 3, TO_DATE('2024-07-07', 'YYYY-MM-DD'), 31, 7);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '사이즈가 크지만 괜찮아요.', 4, TO_DATE('2024-07-08', 'YYYY-MM-DD'), 32, 8);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '무난해요. 만족합니다.', 3, TO_DATE('2024-07-09', 'YYYY-MM-DD'), 33, 9);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '착화감이 좋지 않아요. 실망입니다.', 2, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 34, 10);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '아주 좋아요! 자주 신을게요.', 5, TO_DATE('2024-07-11', 'YYYY-MM-DD'), 35, 11);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '디자인이 예쁘지만 불편해요.', 3, TO_DATE('2024-07-12', 'YYYY-MM-DD'), 36, 12);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '가격 대비 만족합니다.', 4, TO_DATE('2024-07-13', 'YYYY-MM-DD'), 37, 16);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '배송이 빨라서 좋았어요.', 5, TO_DATE('2024-07-14', 'YYYY-MM-DD'), 38, 17);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '신발이 너무 단단해서 발이 아파요.', 2, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 39, 18);
INSERT INTO REVIEW (REVIEWNO, CONTENTS, RATING, RDATE, SHOESNO, MEMBERNO) VALUES (review_seq.nextval, '가볍고 편해요. 잘 신을게요.', 5, TO_DATE('2024-07-16', 'YYYY-MM-DD'), 40, 19);

commit;

rollback;