name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          whoami
          ls -al
    - name: Copy war file to remote
      uses: appleboy/scp-action@v0.1.10
      with:
        username: ${{ secrets.SERVER_USERNAME }}
        host: ${{ secrets.SERVER_HOST }}
        key: ${{ secrets.SERVER_KEY }}
        source: "./build/libs/*.war"
        target: "/home/ubuntu/deploy"
        strip_components: 2
    - name: Execute deploy script
      uses: appleboy/ssh-action@v0.1.10
      with:
        username: ${{ secrets.SERVER_USERNAME }}
        host: ${{ secrets.SERVER_HOST }}
        key: ${{ secrets.SERVER_KEY }}
        script_stop: true
        script: |
          chmod +x /home/ubuntu/deploy/deploy.sh
          sh /home/ubuntu/deploy/deploy.sh
    - name: Execute wordcloud script
      uses: appleboy/ssh-action@v0.1.10
      with:
        username: ${{ secrets.SERVER_USERNAME }}
        host: ${{ secrets.SERVER_HOST }}
        key: ${{ secrets.SERVER_KEY }}
        script_stop: false
        script: |
          chmod +x /home/ubuntu/deploy/wordcloud.sh
          nohup sh /home/ubuntu/deploy/wordcloud.sh > /dev/null 2>&1 &

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3.1.0
